# Consider the below code to answer further questions:
# import numpy as np
# list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
# array_list = np.array(object = list_)

# 1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
ANSWER:

Yes, there is a difference in the data type of variables list_ and array_list. The list_ variable is a Python list, while the array_list variable is a NumPy array.

To print the data types of both variables, you can use the type() function. Here's the code to do that:

    import numpy as np

    list_ = ['1', '2', '3', '4', '5']
    array_list = np.array(list_)

    print(type(list_))
    print(type(array_list))

OUTPUT:

    <class 'list'>
    <class 'numpy.ndarray'>


# 2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.
ANSWER:

    import numpy as np

    list_ = ['1', '2', '3', '4', '5']
    array_list = np.array(list_)

    # Printing data type of each element in list_
    for elem in list_:
        print(type(elem))

    # Printing data type of each element in array_list
    for elem in array_list:
        print(type(elem))

OUTPUT:

    <class 'str'>
    <class 'str'>
    <class 'str'>
    <class 'str'>
    <class 'str'>
    <class 'numpy.str_'>
    <class 'numpy.str_'>
    <class 'numpy.str_'>
    <class 'numpy.str_'>
    <class 'numpy.str_'>


# 3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.
ANSWER:

Yes, there will be a difference in the data type of the elements present in both variables list_ and array_list after changing the data type of array_list to int. The elements in list_ will still be of type str, while the elements in array_list will be of type int.

Here's the code to print the data type of each element present in both variables list_ and array_list after the data type of array_list has been changed to int:

    import numpy as np

    list_ = ['1', '2', '3', '4', '5']
    array_list = np.array(object=list_, dtype=int)

    # Printing data type of each element in list_
    for elem in list_:
        print(type(elem))

    # Printing data type of each element in array_list
    for elem in array_list:
        print(type(elem))

OUTPUT:

    <class 'str'>
    <class 'str'>
    <class 'str'>
    <class 'str'>
    <class 'str'>
    <class 'numpy.int64'>
    <class 'numpy.int64'>
    <class 'numpy.int64'>
    <class 'numpy.int64'>
    <class 'numpy.int64'>


# Consider the below code to answer further questions:
# import numpy as np
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
# num_array = np.array(object = num_list)

# 4. Write a code to find the following characteristics of variable, num_array: (i) shape, (ii) size
ANSWER:

    import numpy as np

    num_list = [[1, 2, 3], [4, 5, 6]]
    num_array = np.array(num_list)

    # Finding shape of num_array
    print("Shape of num_array:", num_array.shape)

    # Finding size of num_array
    print("Size of num_array:", num_array.size)

OUTPUT:

    Shape of num_array: (2, 3)
    Size of num_array: 6


# 5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
ANSWER:

    import numpy as np

    # Creating a 3x3 matrix of zeros using np.zeros()
    zeros_array = np.zeros((3, 3))

    print(zeros_array)

OUTPUT:

    [[0. 0. 0.]
     [0. 0. 0.]
     [0. 0. 0.]]


# 6. Create an identity matrix of shape (5,5) using numpy functions?
ANSWER:

    import numpy as np

    # Creating an identity matrix of shape (5, 5) using np.identity()
    identity_matrix = np.identity(5)

    print(identity_matrix)

OUTPUT:

    [[1. 0. 0. 0. 0.]
     [0. 1. 0. 0. 0.]
     [0. 0. 1. 0. 0.]
     [0. 0. 0. 1. 0.]
     [0. 0. 0. 0. 1.]]
